name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Lint
        run: pipenv run flake8 .

      - name: Format check
        run: pipenv run black . --check

      - name: Run tests
        run: pipenv run pytest
